odiseo_backend_security_login:
    path: /login
    methods: [GET]
    defaults:
        _controller: OdiseoBackendBundle:Security:login

odiseo_backend_security_login_check:
    path: /login-check
    methods: [POST]
    defaults:
        _controller: OdiseoBackendBundle:Security:check

odiseo_backend_security_logout:
    path: /logout
    methods: [GET]
    defaults:
        _controller: OdiseoBackendBundle:Security:logout